footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.01

update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

publish_voxel_map: true
#static_map: false
folling_window: true
width: 6.0
height: 6.0
origin_x: -3.0
origin_y: -3.0
resolution: 0.025

obstacle_range: 2.5
max_obstacle_height: 1.0
min_obstacle_height: 0.1
raytrace_range: 3.0

#obstacle_range: 5.5
#raytrace_range: 6.0

#layer definitions
#static:
#    map_topic: /map
#    subscribe_to_updates: true
#
#obstacles_laser:
#    observation_sources: laser
#    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}
#
#inflation:
#    inflation_radius: 1.0
#